// import "./list/ban.js"
// import "./list/pardon.js"
// import "./list/lockdimension.js"
// import "./list/unlockdimension.js"
// import "./list/banlist.js"
// import "./list/sethome.js"
// import "./list/home.js"
// import "./list/nickname.js"
// import './list/mute.js'
// import "./list/unmute.js"
// import "./list/kickall.js"
// import "./list/realname.js"
// import "./list/suicide.js"
// import "./list/warp.js"
// import "./list/setwarp.js"

// Underdevelopment
// import "./list/delwarp.js"
// import "./list/warplist.js"
import "./list/Default/tps.js"
import "./list/Default/delwarp.js"
import "./list/Default/warplist.js"
import "./list/Default/warp.js"
import "./list/Default/suicide.js"
import "./list/Default/setwarp.js"
import "./list/Default/sethome.js"
import "./list/Default/home.js"

// Moderator
import "./list/Moderation/lockdimension.js"
import "./list/Moderation/unlockdimension.js"
import "./list/Moderation/mute.js"
import "./list/Moderation/unmute.js"
import "./list/Moderation/tempban.js"
import "./list/Moderation/ban.js"
import "./list/Moderation/pardon.js"
import "./list/Moderation/realname.js"
import "./list/Moderation/nickname.js"
import "./list/Moderation/kickall.js"
import "./list/Moderation/banlist.js"